ALTER TABLE "Clip"
  ADD COLUMN IF NOT EXISTS "emotionalDensity" INTEGER,
  ADD COLUMN IF NOT EXISTS "quotability" INTEGER,
  ADD COLUMN IF NOT EXISTS "needsReview" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "textSimilarity" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "detectedWeakEnding" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "detectedLastWords" TEXT,
  ADD COLUMN IF NOT EXISTS "wasAdjustedByAi" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "adjustmentNotes" TEXT;
