ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "openingStrength" INTEGER;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "contextIndependenceScore" INTEGER;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "riskOfBadCut" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "suggestedCaptionTitle" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "firstThreeSecondsHook" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "shareabilityReason" TEXT;
