ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'COMEDY';
ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'GAMING';
ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'MYSTERY';
ALTER TYPE "ContentType" ADD VALUE IF NOT EXISTS 'NEWS';
