ALTER TYPE "RenderLayout" ADD VALUE IF NOT EXISTS 'SMART_REFRAME';
ALTER TYPE "RenderLayout" ADD VALUE IF NOT EXISTS 'SMART_CENTER';
ALTER TYPE "RenderLayout" ADD VALUE IF NOT EXISTS 'SPEAKER_CLOSEUP';
ALTER TYPE "RenderLayout" ADD VALUE IF NOT EXISTS 'PODCAST_SPLIT_STATIC';
ALTER TYPE "RenderLayout" ADD VALUE IF NOT EXISTS 'SCREEN_PLUS_FACE';

ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'BOLD_CREATOR';
ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'CLEAN_EDITORIAL';
ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'NEON_TECH';
ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'KARAOKE_PRO';
ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'PODCAST_PRO';
ALTER TYPE "CaptionTheme" ADD VALUE IF NOT EXISTS 'STORY_IMPACT';

ALTER TABLE "Transcript" ADD COLUMN IF NOT EXISTS "wordsJson" JSONB;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "renderEngine" TEXT;
ALTER TABLE "Clip" ADD COLUMN IF NOT EXISTS "renderDurationMs" INTEGER;
